from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from .views import user_preferences, export_hot_investments_csv, search_stocks, add_stock, history_dates

urlpatterns = [
    path('', views.index, name='index'),
    path('akcie/', views.akcie_list, name='akcie_list'),
    path('akcie/<int:pk>/', views.akcie_detail, name='akcie_detail'),
    path('akcie/create/', views.akcie_create, name='akcie_create'),
    path('akcie/<int:pk>/update/', views.akcie_update, name='akcie_update'),
    path('akcie/<int:pk>/delete/', views.akcie_delete, name='akcie_delete'),
    path('akcie/export/', views.export_akcie_csv, name='export_akcie_csv'),
    path('akcie/import/', views.import_akcie_csv, name='import_akcie_csv'),
    path('akcie/report/', views.generate_akcie_pdf, name='generate_akcie_pdf'),
    path('akcie/import_excel/', views.import_excel, name='import_excel'),
    path('akcie/export_excel/', views.export_excel, name='export_excel'),
    path('akcie/export_json/', views.export_akcie_json, name='export_akcie_json'),
    path('akcie/search/', search_stocks, name='search_stocks'),
    path('akcie/add/', add_stock, name='add_stock'),
    path('akcie/history_dates/', history_dates, name='history_dates'),
    path('transakce/', views.transakce_list, name='transakce_list'),
    path('transakce/<int:pk>/', views.transakce_detail, name='transakce_detail'),
    path('transakce/create/', views.transakce_create, name='transakce_create'),
    path('transakce/<int:pk>/update/', views.transakce_update, name='transakce_update'),
    path('transakce/<int:pk>/delete/', views.transakce_delete, name='transakce_delete'),
    path('transakce/export/', views.export_transakce_csv, name='export_transakce_csv'),
    path('transakce/report/', views.generate_transakce_pdf, name='generate_transakce_pdf'),
    path('dividendy/', views.dividenda_list, name='dividenda_list'),
    path('dividendy/<int:pk>/', views.dividenda_detail, name='dividenda_detail'),
    path('dividendy/create/', views.dividenda_create, name='dividenda_create'),
    path('dividendy/<int:pk>/update/', views.dividenda_update, name='dividenda_update'),
    path('dividendy/<int:pk>/delete/', views.dividenda_delete, name='dividenda_delete'),
    path('dividendy/export/', views.export_dividendy_csv, name='export_dividendy_csv'),
    path('dividendy/report/', views.generate_dividenda_pdf, name='generate_dividenda_pdf'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/export/', views.export_dashboard_pdf, name='export_dashboard_pdf'),
    path('dashboard/export_graphs_pdf/', views.export_dashboard_graphs_pdf, name='export_dashboard_graphs_pdf'),
    path('aktivity/', views.aktivity_list, name='aktivity_list'),
    path('aktivity/export_csv/', views.export_aktivity_csv, name='export_aktivity_csv'),
    path('aktivity/export_pdf/', views.export_aktivity_pdf, name='export_aktivity_pdf'),
    path('login/', auth_views.LoginView.as_view(template_name='akcie/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('preferences/', user_preferences, name='user_preferences'),
    path('export_all_data_zip/', views.export_all_data_zip, name='export_all_data_zip'),
    path('export-hot-investments/', export_hot_investments_csv, name='export_hot_investments_csv'),
    path('convert_to_czk/', views.convert_to_czk_api, name='convert_to_czk_api'),
]
