# Generated by Django 4.2.21 on 2025-05-13 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Akcie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('pocet_ks', models.IntegerField()),
                ('cena_za_kus', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hodnota', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nakup', models.DecimalField(decimal_places=2, max_digits=15)),
                ('zisk_ztrata', models.DecimalField(decimal_places=2, max_digits=15)),
                ('dividenda', models.DecimalField(decimal_places=2, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Transakce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('typ', models.CharField(choices=[('nákup', 'Nákup'), ('prodej', 'Prodej')], max_length=50)),
                ('mnozstvi', models.IntegerField()),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('akcie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='akcie.akcie')),
            ],
        ),
        migrations.CreateModel(
            name='Dividenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('castka', models.DecimalField(decimal_places=2, max_digits=10)),
                ('akcie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividendy', to='akcie.akcie')),
            ],
        ),
    ]
