# Generated by Django 4.2.21 on 2025-05-13 12:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akcie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aktivita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akce', models.CharField(max_length=255)),
                ('uzivatel', models.CharField(blank=True, max_length=255, null=True)),
                ('datum_cas', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
