# Generated by Django 4.2.21 on 2025-05-13 18:35

import akcie.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akcie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcie',
            name='user',
            field=models.ForeignKey(default=akcie.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='akcie', to=settings.AUTH_USER_MODEL),
        ),
    ]
