# Generated by Django 4.2.21 on 2025-05-14 08:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('akcie', '0002_akcie_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcie',
            name='cas',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='akcie',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
