# Generated by Django 4.2.21 on 2025-05-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('akcie', '0003_customuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
    ]
