# Generated by Django 4.2.21 on 2025-05-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akcie', '0004_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='akcie',
            name='mena',
            field=models.CharField(blank=True, default='CZK', help_text='Měna, ve které je akcie obchodována (např. USD, EUR, CZK)', max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='akcie',
            name='ticker',
            field=models.CharField(blank=True, help_text='Oficiální ticker akcie dle burzy (např. AAPL pro Apple Inc.)', max_length=20, null=True),
        ),
    ]
