# Generated by Django 4.2.21 on 2025-05-15 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akcie', '0005_akcie_mena_akcie_ticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(blank=True, max_length=30)),
                ('adresa', models.CharField(blank=True, max_length=255)),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('poznamka', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='klient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazev', models.CharField(max_length=100)),
                ('popis', models.TextField(blank=True)),
                ('datum_vytvoreni', models.DateTimeField(auto_now_add=True)),
                ('klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolia', to='akcie.klient')),
            ],
        ),
    ]
