# Generated by Django 4.2.21 on 2025-05-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('akcie', '0006_klient_portfolio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='receive_monthly_reports',
            field=models.BooleanField(default=True, verbose_name='Zasílat měsíční PDF report e-mailem'),
        ),
    ]
