# Generated by Django for removing 'dividenda' from Akcie
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('akcie', '0007_alter_customuser_receive_monthly_reports'),
    ]
    operations = [
        migrations.RemoveField(
            model_name='akcie',
            name='dividenda',
        ),
    ]
