# Generated by Django 4.2.21 on 2025-05-15 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('akcie', '0008_remove_akcie_dividenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='klient',
            name='poradce',
            field=models.ForeignKey(blank=True, help_text='Poradce, který spravuje tohoto klienta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='klienti', to=settings.AUTH_USER_MODEL),
        ),
    ]
